
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: example_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: example_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8080:8080"
      #TODO: add envirorment variables related to the env
    depends_on:
      - db

